// Cấu hình Ma trận Phân Quyền Vai Trò Hệ Thống Luxe Motors
export const ROLES_CONFIG = {
  admin: {
    key: 'admin',
    label: 'Admin (Quản Trị Viên Tối Cao)',
    color: 'bg-[#D4AF37]/15 text-[#D4AF37] border-[#D4AF37]/40',
    badgeBg: '#D4AF37',
    icon: 'Crown',
    description: 'Toàn quyền điều hành, phân quyền tài khoản, sửa kho xe, quản lý doanh thu và cấu hình website.',
    permissions: [
      'Quản lý tất cả tài khoản',
      'Phân quyền người dùng',
      'Thêm/sửa/xóa kho xe',
      'Quản lý đơn hàng & cọc xe',
      'Xem toàn bộ doanh thu',
      'Cấu hình website hệ thống',
    ],
  },
  giam_doc: {
    key: 'giam_doc',
    label: 'Giám Đốc (Executive Director)',
    color: 'bg-[#C5A028]/15 text-[#E6C200] border-[#E6C200]/40',
    badgeBg: '#E6C200',
    icon: 'Briefcase',
    description: 'Xem toàn bộ báo cáo doanh thu, lợi nhuận, phễu đơn hàng và phê duyệt các mức giảm giá lớn.',
    permissions: [
      'Xem toàn bộ doanh thu',
      'Xem báo cáo bán xe',
      'Xem lợi nhuận kinh doanh',
      'Xem dữ liệu khách hàng',
      'Xem phễu đơn hàng',
      'Phê duyệt đơn hàng & giảm giá lớn',
    ],
    limitations: ['Không được sửa cấu hình hệ thống website'],
  },
  quan_ly: {
    key: 'quan_ly',
    label: 'Quản Lý (Showroom Manager)',
    color: 'bg-blue-500/15 text-blue-400 border-blue-500/40',
    badgeBg: '#3B82F6',
    icon: 'UserCheck',
    description: 'Điều hành kho xe, tồn kho, quản lý nhân viên sales, duyệt đơn hàng và xem báo cáo bộ phận.',
    permissions: [
      'Quản lý danh sách xe',
      'Quản lý tồn kho',
      'Quản lý nhân viên bán hàng',
      'Quản lý dữ liệu khách hàng',
      'Quản lý đơn hàng',
      'Duyệt báo giá theo hạn mức',
      'Xem báo cáo bộ phận',
    ],
  },
  sales: {
    key: 'sales',
    label: 'Nhân Viên Bán Hàng (Sales Executive)',
    color: 'bg-purple-500/15 text-purple-400 border-purple-500/40',
    badgeBg: '#A855F7',
    icon: 'ShoppingBag',
    description: 'Tư vấn xe, tạo khách hàng mới, lập báo giá, tạo đơn hàng cọc và xem lịch hẹn của cá nhân.',
    permissions: [
      'Xem kho xe',
      'Tạo khách hàng mới',
      'Tạo báo giá tư vấn',
      'Tư vấn & chốt xe',
      'Tạo đơn hàng & yêu cầu cọc',
      'Quản lý khách hàng cá nhân',
      'Xem lịch hẹn cá nhân',
    ],
  },
  cskh: {
    key: 'cskh',
    label: 'Chăm Sóc Khách Hàng (Customer Service)',
    color: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/40',
    badgeBg: '#10B981',
    icon: 'Headphones',
    description: 'Quản lý lịch hẹn Concierge, gọi chăm sóc khách hàng, tiếp nhận phản hồi và xử lý khiếu nại.',
    permissions: [
      'Xem thông tin khách hàng',
      'Quản lý lịch hẹn Concierge',
      'Gọi & chăm sóc khách hàng',
      'Ghi nhận phản hồi',
      'Xử lý khiếu nại',
      'Chăm sóc sau bán hàng',
    ],
    limitations: ['Không được sửa giá xe hoặc doanh thu'],
  },
  user: {
    key: 'user',
    label: 'Khách Hàng VIP (Client)',
    color: 'bg-slate-500/15 text-slate-300 border-slate-500/30',
    badgeBg: '#64748B',
    icon: 'User',
    description: 'Khách hàng thành viên xem siêu xe, đặt lịch xem xe, cọc xe online và quản lý hồ sơ cá nhân.',
    permissions: [
      'Xem kho siêu xe',
      'Đặt lịch lái thử tận nơi',
      'Tạo đơn đặt cọc xe',
      'Quản lý xe yêu thích',
      'Quản lý đơn hàng cá nhân',
    ],
  },
};

// Danh sách tất cả tính năng kiểm tra phân quyền
export const PERMISSION_ITEMS = [
  { id: 'manage_users', label: 'Quản lý tất cả tài khoản', category: 'Hệ thống' },
  { id: 'assign_roles', label: 'Phân quyền người dùng', category: 'Hệ thống' },
  { id: 'config_site', label: 'Cấu hình website', category: 'Hệ thống' },
  { id: 'manage_cars', label: 'Thêm/sửa/xóa danh sách xe & tồn kho', category: 'Kho Xe' },
  { id: 'view_revenue', label: 'Xem toàn bộ doanh thu & lợi nhuận', category: 'Tài chính' },
  { id: 'approve_discounts', label: 'Phê duyệt đơn hàng & giảm giá lớn', category: 'Bán hàng' },
  { id: 'manage_sales_team', label: 'Quản lý nhân viên bán hàng', category: 'Nhân sự' },
  { id: 'manage_orders', label: 'Quản lý đơn hàng & yêu cầu cọc', category: 'Bán hàng' },
  { id: 'manage_leads', label: 'Quản lý thông tin khách hàng', category: 'Khách hàng' },
  { id: 'manage_appointments', label: 'Quản lý lịch hẹn Concierge & CSKH', category: 'CSKH' },
  { id: 'handle_complaints', label: 'Xử lý khiếu nại & phản hồi', category: 'CSKH' },
];
